### ISSUE TITLE
Crash when doing /back to get to my gravestone

### ISSUE THREAD

**Issue by aaronhnsy** [janagyjr/tcgs-chillpack#3] opened 2018-01-05 23:48 UTC
I crashed when i did /back with this crash log 
https://pastebin.com/7reyA9fu

**Comment by janagyjr** [comment] 2018-01-06 18:30
Mod author no longer supports this version of Inventory Tweaks (nor will address what the issue is). Closing the issue, sorry MrRandom.

**Closed as completed by janagyjr** 2018-01-06 18:30 UTC
Labels: wontfix
